export const LOAD_ROOM_LIST = 'LOAD_ROOM_LIST';
export const LOAD_ROOM_LIST_SUCCESS = 'LOAD_ROOM_LIST_SUCCESS';
export const LOAD_ROOM_LIST_FAIL = 'LOAD_ROOM_LIST_FAIL';

export const LOAD_ROOM_DETAIL = 'LOAD_ROOM_DETAIL';
